const alunos6 = [
  { nome: "Alanis Vitória Couto Veloso", foto: "fotos/Alanis.jpg" }
  {nome:"Ana Beatriz Banadia Brajão","fotos":"fotos/ana2.jpg"},
  {nome:"Aysha Radyja Gaeta Donatangelo Teodoro de Godoy","fotos":"fotos/aysha3.jpg"},
  {nome:"Arthur Miguel","fotos":"fotos/arthur4.jpg"},
  {nome:"Christopher da Silva Carvalho","fotos":"fotos/christopher5.jpg"},
  {nome:"Davi Lucas Moreira de Campos","fotos":"fotos/davi6.jpg"},
  {nome:"Davi Luccas de Miranda Medeiros","fotos":"fotos/davi7.jpg"},
  {nome:"Guilherme Jorge dos Santos","fotos":"fotos/guilherme8.jpg"},
  {nome:"Gustavo Oliveira de Almeida","fotos":"fotos/gustavo9.jpg"},
  {nome:"Isabela Zarpelon Retorta","fotos":"fotos/isabela10.jpg"},
  {nome:"Isis Rafaela Cardoso de Souza","fotos":"fotos/isis11.jpg"},
  {nome:"Kaique Wender de Oliveira Vaz","fotos":"fotos/kaique12.jpg"},
  {nome:"Laura Alves da Cunha de Próspero","fotos":"fotos/laura13.jpg"},
  {nome:"Livia Sanches de Almeida Batista","fotos":"fotos/livia14.jpg"},
  {nome:"Lorena Gonçalves Andrade","fotos":"fotos/lorena15.jpg"},
  {nome:"Luana Castro Gomes","fotos":"fotos/luana16.jpg"},
  {nome:"Lucas Gabriel da Cunha Oliveira","fotos":"fotos/lucas17.jpg"},
  {nome:"Maitê Oliveira Sérgio","fotos":"fotos/maite18.jpg"},
  {nome:"Maria Eduarda Almeida Martins","fotos":"fotos/maria19.jpg"},
  {nome:"Maria Clara Ramos Geraldo","fotos":"fotos/maria20.jpg"},
  {nome:"Miguel Fish Amistá","fotos":"fotos/miguel21.jpg"},
  {nome:"Nicolas Favero Leme","fotos":"fotos/nicolas22.jpg"},
  {nome:"Rafael Stefano de Campos Silva","fotos":"fotos/rafael23.jpg"},
  {nome:"Sarah Cavalcante Ferreira","fotos":"fotos/sarah24.jpg"},
  {nome:"Silas de Souza Nobrega Arantes Machado","fotos":"fotos/silas25.jpg"},
  {nome:"Yasmim Mércia de Godoy Aguiar","fotos":"fotos/yasmim26.jpg"}
];

const alunos7 = [
  {nome:"Alice Alves Rodrigues","foto":"fotos/alice1.jpg"},
  {nome:"Ana Julia de Oliveira e Santos","foto":"fotos/ana2.jpg"},
  {nome:"Enzo Raimundo da Silva Brandão","foto":"fotos/enzo3.jpg"},
  {nome:"Gabriel Stefano Campos Silva","foto":"fotos/gabriel4.jpg"},
  {nome:"Gustavo Moraes da Cunha","foto":"fotos/gustavo5.jpg"},
  {nome:"Heitor Amarins Mancilha de Camargo","foto":"fotos/heitor6.jpg"},
  {nome:"Helloísa Bernardes de Faria","foto":"fotos/hellois a7.jpg"},
  {nome:"Isabella Teixeira de Souza","foto":"fotos/isabella8.jpg"},
  {nome:"Laura Lucio Prado","foto":"fotos/laura9.jpg"},
  {nome:"Lorena de Moraes Crispim","foto":"fotos/lorena10.jpg"},
  {nome:"Luiza Franco de Oliveira","foto":"fotos/luiza11.jpg"},
  {nome:"Maria Luíza da Silva Carvalho","foto":"fotos/maria12.jpg"},
  {nome:"Matheus Sato de Oliveira","foto":"fotos/matheus13.jpg"},
  {nome:"Miguel de Moraes Moura Servilha","foto":"fotos/miguel14.jpg"},
  {nome:"Nara Souza Nunes","foto":"fotos/nara15.jpg"},
  {nome:"Rafaella Faralhi","foto":"fotos/rafaella16.jpg" },
  {nome:"Renato Junior Petrillo Da Silva","foto":"fotos/renato17.jpg" },
  {nome:"Théo Henrique Lugli Ramos","foto":"fotos/theo18.jpg" },
  {nome:"Thiago Grigorio da Silva","foto":"fotos/thiago19.jpg" },
  {nome:"Vinicius Gabriel Meira de Camargo","foto":"fotos/vinicius20.jpg" },
  {nome:"Vinicius Gonçalves Coelho","foto":"fotos/vinicius21.jpg" }
];

const alunos8 = [
  {nome:"Ana Clara Mendes da Silva","foto":"fotos/ana1.jpg"},
  {nome:"Benjamim Nascimento Gomes Alvarez","foto":"fotos/benjamim2.jpg"},
  {nome:"Erick Hildegarth Paixão","foto":"fotos/erick3.jpg"},
  {nome:"Giovana Lima Sacomani","foto":"fotos/giovana4.jpg"},
  {nome:"Laura Peron Alves","foto":"fotos/laura5.jpg"},
  {nome:"Lorenzo Ochsendorf","foto":"fotos/lorenzo6.jpg"},
  {nome:"Nicolas Cauã de Souza Santos","foto":"fotos/nicolas7.jpg"},
  {nome:"Manuella Moraes Dian","foto":"fotos/manuella8.jpg"},
  {nome:"Maria Eduarda Ribeiro","foto":"fotos/maria9.jpg"},
  {nome:"Matheus Zarpelon Retorta","foto":"fotos/matheus10.jpg"},
  {nome:"Miguel Bernardo de Souza Oliveira","foto":"fotos/miguel11.jpg"},
  {nome:"Murilo Mensato Alves","foto":"fotos/murilo12.jpg"},
  {nome:"Pedro Ferreira Lisboa da Silva","foto":"fotos/pedro13.jpg"},
  {nome:"Pedro Henrique Braga Genú","foto":"fotos/pedro14.jpg"},
  {nome:"Thiago Caldeira Marques","foto":"fotos/thiago15.jpg"},
  {nome:"Samuel Henrique de Oliveira Paula","foto":"fotos/samuel16.jpg"},
  {nome:"Sofia Silva Neres","foto":"fotos/sofia17.jpg"},
  {nome:"Valentina Leme Jameli","foto":"fotos/valentina18.jpg"},
  {nome:"Vinícius de Oliveira Riveiro Portas","foto":"fotos/vinicius19.jpg"},
  {nome:"Yuri Barbosa da Silva","foto":"fotos/yuri20.jpg"}
];

const alunos9 = [
  {nome:"Caio da Silva Francisco","foto":"fotos/caio1.jpg"},
  {nome:"Caio Rodrigues Mancinelli","foto":"fotos/caio2.jpg"},
  {nome:"Davi Marques de Oliveira","foto":"fotos/davi3.jpg"},
  {nome:"Davi Silva Neres","foto":"fotos/davi4.jpg"},
  {nome:"Emilly Aparecida de Oliveira","foto":"fotos/emilly5.jpg"},
  {nome:"Giovanni Felipe Garcia Oliveira","foto":"fotos/giovanni6.jpg"},
  {nome:"Gustavo Henrique da Silva","foto":"fotos/gustavo7.jpg"},
  {nome:"Isabella Ferreira Bueno","foto":"fotos/isabella8.jpg"},
  {nome:"Juan Pietro Carobrez Godoy Rodrigues","foto":"fotos/juan9.jpg"},
  {nome:"Julia Gallo Rezende","foto":"fotos/julia10.jpg"},
  {nome:"Luana Priscila Leite Souza","foto":"fotos/luana11.jpg"},
  {nome:"Manuela Pereira Gomes","foto":"fotos/manuela12.jpg"},
  {nome:"Paulo Manoel de Melo","foto":"fotos/paulo13.jpg"},
  {nome:"Sara Vitória da Silva Panizza","foto":"fotos/sara14.jpg"},
  {nome:"Vinícius Aparecido Leme Ventura","foto":"fotos/vinicius15.jpg"}
];
